version: "3"
services:
  redis-server:
    image: "redis"
    restart: always
  node-app:
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
  student:
    restart: on-failure
    image: "hello-world"
