node {
def commit_id 
stage('Preparation'){
checkout scm
sh "git rev-parse --short HEAD > .git/commit-id"
 commit_id = readFile('.git/commit-id').trim()
}
stage('test'){
nodejs(nodeJSInstallationName: 'nodejs'){
 sh 'npm install'
}
}
stage('docker build/publish'){
docker.withRegistry('https://index.docker.io/v1/','dockerhub'){
 def app = docker.build("manshaehsan/jenkins-tutorials:${commit_id}",'./visits/').push()
}
}
post {
        always {
            emailext body: 'Visit App build is successful', recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: 'Test'
        }
    }
}
